<?xml version="1.0"?>
<package format="2">
  <name>pal_sea_arm</name>
  <version>0.1.7</version>
  <description>The pal_sea_arm package</description>

  <maintainer email="narcis.miguel@pal-robotics.com">Narcis Miguel</maintainer>

  <license>Propietary</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>pal_sea_arm_controller_configuration</exec_depend>
  <exec_depend>pal_sea_arm_description</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
