<?xml version="1.0"?>
<package format="2">
  <name>pal_sea_arm_description</name>
  <version>0.1.4</version>
  <description>The pal_sea_arm_description package</description>

  <maintainer email="narcis.miguel@pal-robotics.com">Narcis Miguel</maintainer>

  <license>Propietary</license>

  <buildtool_depend>catkin</buildtool_depend>

  <!--exec_depend>gazebo_plugins</exec_depend>
  <exec_depend>gazebo_ros_control</exec_depend-->
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>pal_pro_gripper_description</exec_depend>
  <exec_depend>pal_urdf_utils</exec_depend>

  <test_depend>rostest</test_depend>
  <test_depend>urdf_test</test_depend>

</package>
